nelmio_api_doc:
    documentation:
        info:
            title: POC Symfony API
            description: API pour la gestion des jeux vidéo
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Exclude /api/doc